name: Submit Pull Request

on:
  push:

jobs:
  SubmitPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Pull Request
        uses: iaia/submit_pull_request@test
        env:
          GITHUB_ACCESS_TOKEN: ${{secrets.github_token}}
          LABEL: WIP
