name: Submit Pull Request

on:
  push:

jobs:
  SubmitPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Submit Pul Request
        uses: iaia/submit_pull_request@feature/21-draft
        env:
          GITHUB_ACCESS_TOKEN: ${{secrets.github_token}}
          LABEL: WIP
          DRAFT: true
          DEBUG: true
